[dados]
[[dados.resposta]]
rid = 1
rtext = """
Campo Grande é a Capital da América do Sul
"""
[[dados.resposta.pergunta]]
rid = 1
fid = 1
ptext = """
Qual é a capital da América do Sul
"""
[[dados.resposta.pergunta]]
rid = 1
fid = 2
ptext = """
Quem é a capital da América do Sul
"""