[package]
name = "estimulo"
version = "0.1.0"
edition = "2021"

[dependencies]
	gcc = "0.3.55"
	libsqlite3-sys = "0.30.1"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
		version 	= "0.32.0"
    	features 	= ["bundled"]
