[dados]
    [[dados.arquivo]]
        arquivo_nomeorigem = "ARQUIVO 4 GRCP - 2024-04 - V.1.0.csv"
        arquivo_qtde_parte = 4
        arquivo_nome_parte = "ARQUIVO 4 GRCP - 2024-04 - V.1.0 - Parte "
        
    [[dados.arquivo]]
        arquivo_nomeorigem = "ARQUIVO 2 PESSOAS  4534-03 - v.1.2.csv"
        arquivo_qtde_parte = 4
        arquivo_nome_parte = "3 Pessoas - 03_2024 - v.1.36.3 - Parte "