[dados]
    [[dados.arquivo]]
        arquivo_nomeorigem = "ARQUIVO 2 PESSOAS  2024-03 - v.1.1.csv"
        arquivo_qtde_parte = 4
        arquivo_nome_parte = "2 Pessoas - 03_2024 - v.1.36.2 - Parte "