[package]
name = "arquivosplit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2.33"
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
toml = "0.8.12"
